### ISSUE TITLE
Clarification on "fm" module import

### ISSUE THREAD

**Issue by bridadan** [jamesbeyond/mbed-fastmodel-agent#2]
Hi @jamesbeyond, one other thing I spotted when reviewing this module: https://github.com/jamesbeyond/mbed-fastmodel-agent/blob/master/fastmodel_agent/fastmodel_agent.py#L62

Throughout the agent you're calling `import fm.debug`. Where is this module located? I might be missing something incredibly obvious, so sorry for the silly question if that's the case 😄

**Comment by jamesbeyond** [comment]
Hi @bridadan,
Thanks for the reviewing.
It is a valid question. maybe I should add more explains in the README.MD.
This will throw errors if user settings are not correct.

It comes from the above line 61, where trying to add 'PVLIB_HOME' to python module search path.

'PVLIB_HOME' is the environment variable, when you install the Fast Model product, it will be created automatically.

fm.debug is the Fastmodel PyCADI module(part of Fast Models product), which allow the model to be controlled form python scripts.

**Comment by bridadan** [comment]
Ah gotcha, didn't realize it came with a Python library! It sounds like its a pretty automatic step so it might not be necessary to add it to the README. I haven't actually used the Fast Models, so I'll close this and leave it up to you!
